# Generated by Django 5.2.7 on 2025-11-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailing", "0001_initial"),
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="messaging.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
