# Generated by Django 5.2.7 on 2025-11-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_message",
                    models.CharField(max_length=150, verbose_name="Тема сообщения"),
                ),
                (
                    "text_message",
                    models.TextField(max_length=500, verbose_name="Текст сообщения"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
